spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false

server:
    port: ${PORT:8080}